In [15]:
import pandas as pd
import numpy as np

In [30]:
data= pd.read_csv("/Users/prabhavvalecha/Downloads/RockMine.csv.csv - RockMine.csv.csv.csv",header=None)
print(data)

         0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

         9   ...      51      52      53      54      55      56      57  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036

         58      59  60
0    0.0090  0.0032   R
1    0.0052  0.0044   R
2    0.0095  0.0078   R
3    0.0040  0.0117   R
4    0.0107  0.0094   R
..      ...     ...  ..
203  0.0193  0.0157   M
204  0.0062  0.0067   M
205  0.0077  0.0031   M
206  0.0036  0.0048   M
207  0.0061  0.0115   M

[208 rows x 61 columns]

In [31]:
b=len(data.columns)

In [32]:
a=[]
for i in range(1,len(data.columns)+1):
    a.append("C"+str(i))

In [33]:
a

['C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'C22',
 'C23',
 'C24',
 'C25',
 'C26',
 'C27',
 'C28',
 'C29',
 'C30',
 'C31',
 'C32',
 'C33',
 'C34',
 'C35',
 'C36',
 'C37',
 'C38',
 'C39',
 'C40',
 'C41',
 'C42',
 'C43',
 'C44',
 'C45',
 'C46',
 'C47',
 'C48',
 'C49',
 'C50',
 'C51',
 'C52',
 'C53',
 'C54',
 'C55',
 'C56',
 'C57',
 'C58',
 'C59',
 'C60',
 'C61']

In [34]:
data.columns=a

In [35]:
data.head()
df3=data["C61"]

In [36]:
for i in a:
    print(data[i].nunique())

177
182
190
181
193
196
195
201
205
207
203
206
198
202
203
203
202
204
206
203
200
203
199
201
198
194
190
194
197
202
207
205
205
206
205
205
206
206
204
206
204
208
205
196
205
199
202
204
193
154
160
144
134
134
129
122
121
124
119
109
2

In [37]:

get_unique=data.nunique()
df2=get_unique.sort_values().index
df2=list(df2)

df2.remove("C61")
print(df2)

data= data[df2]

data

['C60', 'C59', 'C57', 'C56', 'C58', 'C55', 'C54', 'C53', 'C52', 'C50', 'C51', 'C1', 'C4', 'C2', 'C3', 'C27', 'C5', 'C49', 'C28', 'C26', 'C7', 'C6', 'C44', 'C29', 'C13', 'C25', 'C46', 'C23', 'C21', 'C24', 'C8', 'C47', 'C17', 'C14', 'C30', 'C11', 'C22', 'C16', 'C15', 'C20', 'C48', 'C39', 'C41', 'C18', 'C33', 'C43', 'C36', 'C35', 'C32', 'C45', 'C9', 'C37', 'C40', 'C38', 'C34', 'C12', 'C19', 'C10', 'C31', 'C42']

,C60,C59,C57,C56,C58,C55,C54,C53,C52,C50,...,C9,C37,C40,C38,C34,C12,C19,C10,C31,C42
0,0.0032,0.0090,0.0180,0.0167,0.0084,0.0072,0.0159,0.0065,0.0027,0.0324,...,0.3109,0.6692,0.2744,0.6097,0.7547,0.1582,0.5078,0.2111,0.1307,0.2834
1,0.0044,0.0052,0.0140,0.0191,0.0049,0.0094,0.0048,0.0089,0.0084,0.0061,...,0.3337,0.3835,0.1970,0.1057,0.2341,0.6552,0.8024,0.2872,0.3788,0.0583
2,0.0078,0.0095,0.0316,0.0244,0.0164,0.0180,0.0095,0.0166,0.0232,0.0106,...,0.5598,0.6116,0.4719,0.6756,0.2709,0.7060,0.8929,0.6194,0.8512,0.2587
3,0.0117,0.0040,0.0050,0.0073,0.0044,0.0085,0.0150,0.0036,0.0121,0.0294,...,0.0598,0.5408,0.9167,0.8814,0.3497,0.1992,0.4060,0.1264,0.6260,0.5006
4,0.0094,0.0107,0.0072,0.0015,0.0048,0.0110,0.0105,0.0054,0.0031,0.0046,...,0.3564,0.4604,0.2430,0.3217,0.0981,0.3952,0.2032,0.4459,0.5103,0.2444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0157,0.0193,0.0065,0.0101,0.0115,0.0033,0.0199,0.0098,0.0116,0.0290,...,0.2328,0.0969,0.1200,0.1411,0.1472,0.2933,0.2034,0.2684,0.6041,0.1036
204,0.0067,0.0062,0.0034,0.0063,0.0032,0.0063,0.0135,0.0093,0.0061,0.0179,...,0.1030,0.1159,0.0345,0.1226,0.2131,0.3425,0.2120,0.2154,0.7691,0.0824
205,0.0031,0.0077,0.0140,0.0089,0.0138,0.0062,0.0051,0.0029,0.0160,0.0235,...,0.1258,0.1066,0.0325,0.1440,0.1786,0.2374,0.1962,0.2529,0.7717,0.0328
206,0.0048,0.0036,0.0034,0.0035,0.0079,0.0036,0.0126,0.0046,0.0086,0.0241,...,0.1945,0.1572,0.0849,0.1823,0.0969,0.2812,0.2828,0.2354,0.6893,0.1367
207,0.0115,0.0061,0.0040,0.0061,0.0036,0.0039,0.0047,0.0129,0.0146,0.0116,...,0.1843,0.2655,0.0768,0.1713,0.1549,0.2442,0.3714,0.2354,0.7622,0.2076

In [38]:
data=data[data.columns[:b-10]]

In [39]:
data.head()

,C60,C59,C57,C56,C58,C55,C54,C53,C52,C50,...,C39,C41,C18,C33,C43,C36,C35,C32,C45,C9
0,0.0032,0.0090,0.0180,0.0167,0.0084,0.0072,0.0159,0.0065,0.0027,0.0324,...,0.4943,0.0510,0.2999,0.5121,0.2825,0.8507,0.8537,0.2604,0.2641,0.3109
1,0.0044,0.0052,0.0140,0.0191,0.0049,0.0094,0.0048,0.0089,0.0084,0.0061,...,0.1840,0.1674,0.8874,0.1984,0.1401,0.4182,0.1306,0.2947,0.0621,0.3337
2,0.0078,0.0095,0.0316,0.0244,0.0164,0.0180,0.0095,0.0166,0.0232,0.0106,...,0.5375,0.4647,0.7551,0.1862,0.2129,0.3043,0.4232,0.5045,0.2111,0.5598
3,0.0117,0.0040,0.0050,0.0073,0.0044,0.0085,0.0150,0.0036,0.0121,0.0294,...,0.9857,0.6121,0.2281,0.6120,0.3210,0.3012,0.3953,0.7340,0.4295,0.0598
4,0.0094,0.0107,0.0072,0.0015,0.0048,0.0110,0.0105,0.0054,0.0031,0.0046,...,0.2828,0.1979,0.6193,0.2881,0.1847,0.4181,0.1951,0.5459,0.0692,0.3564

In [47]:
# a=data.columns
# for i in a:
#     m=data[i].mean()
#     s=data[i].std()
#     data[i]=(data[i]-m)%s
for i in data:
  m=data[i].mean()
  std=data[i].std()
  data[i]=(data[i]-mean)/std
print(data)

          C60       C59       C57       C56       C58       C55       C54  \
0   -0.449315 -1.204529  0.938327 -0.148977 -1.412675  0.715669  0.492517
1    0.368649  0.119679 -1.411258  1.273738  0.234879 -1.663146 -1.297839
2   -0.743130 -0.926495 -1.268219  1.015213 -0.563801 -0.927074  0.917017
3   -1.514091 -0.547601  0.098932  1.079431 -0.042501  1.348380  0.068395
4    0.347489 -0.259215  1.391204  1.041557  0.179403 -0.884425  1.388264
..        ...       ...       ...       ...       ...       ...       ...
203  1.212456  1.085697  0.980026 -0.661089  0.307087 -1.182466 -1.062975
204 -1.492931  0.675745 -0.840902  0.486633 -0.708216  0.277638 -0.638474
205 -0.517479  1.509845 -1.411258 -1.372447  1.583039  0.228967 -1.156465
206  0.641304 -0.770028 -0.840902 -1.173202  1.899165 -1.036455 -1.062595
207  1.778926  0.620138 -0.488464  0.368074 -0.486311 -0.890445 -1.344964

          C53       C52       C50  ...       C39       C41       C18  \
0   -0.328844  1.295748  1.146855  ...  1.235870  0.213637 -0.401618
1    0.797227 -0.080532  1.391271  ... -0.741246 -0.889174  0.469141
2    1.097354 -1.643623 -0.783510  ... -1.534919 -1.794670 -1.318553
3    1.623171  1.213889  0.434980  ... -0.645228  1.176471 -1.371810
4   -0.844960  1.435685  1.035333  ...  1.014998 -0.274386  0.380356
..        ...       ...       ...  ...       ...       ...       ...
203  1.219504  1.038967  0.340063  ... -1.032769 -1.842600 -0.586738
204  0.984905 -0.885172  0.948719  ... -0.869232 -1.114932 -1.171826
205  1.294733 -0.792109 -0.965042  ... -0.583042 -1.260063 -1.293438
206 -1.220317 -0.010563 -0.822666  ... -1.614036  0.177355 -0.879958
207 -0.638672 -1.281890 -0.546219  ...  1.231411  0.892928 -0.163799

          C33       C43       C36       C35       C32       C45        C9
0   -0.341623 -0.937392  1.029941  0.853329 -1.149203 -0.199377 -1.276777
1    1.384317 -1.024964 -1.160377  1.560877 -0.572043 -1.379807 -0.638664
2    1.172324  0.846470  0.793736 -1.379791 -0.629875 -1.441403 -0.937412
3    1.394295  0.052309  0.753410 -1.743360 -0.356218  0.123351 -1.677714
4   -0.645488  0.121547 -1.161677 -0.975405  0.066756 -1.213422 -0.003349
..        ...       ...       ...       ...       ...       ...       ...
203  1.576973  0.455731  1.061979  0.965353  0.214832 -0.721298 -0.149242
204 -0.023632 -1.672768 -1.477505  1.068299 -0.731457 -0.599439 -0.468657
205 -0.209561  0.327028 -1.283682  1.289829 -0.415112 -0.702551  0.169456
206 -1.161572 -0.636796  0.744577  0.870226 -0.771220  0.255919 -1.221160
207  0.916888 -1.760000 -0.733433 -1.379371 -1.434198  0.537132 -1.506632

[208 rows x 51 columns]

<ipython-input-47-c4a6b96003c9>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[i]=(data[i]-mean)/std

In [48]:
data.head()

,C60,C59,C57,C56,C58,C55,C54,C53,C52,C50,...,C39,C41,C18,C33,C43,C36,C35,C32,C45,C9
0,-0.449315,-1.204529,0.938327,-0.148977,-1.412675,0.715669,0.492517,-0.328844,1.295748,1.146855,...,1.235870,0.213637,-0.401618,-0.341623,-0.937392,1.029941,0.853329,-1.149203,-0.199377,-1.276777
1,0.368649,0.119679,-1.411258,1.273738,0.234879,-1.663146,-1.297839,0.797227,-0.080532,1.391271,...,-0.741246,-0.889174,0.469141,1.384317,-1.024964,-1.160377,1.560877,-0.572043,-1.379807,-0.638664
2,-0.743130,-0.926495,-1.268219,1.015213,-0.563801,-0.927074,0.917017,1.097354,-1.643623,-0.783510,...,-1.534919,-1.794670,-1.318553,1.172324,0.846470,0.793736,-1.379791,-0.629875,-1.441403,-0.937412
3,-1.514091,-0.547601,0.098932,1.079431,-0.042501,1.348380,0.068395,1.623171,1.213889,0.434980,...,-0.645228,1.176471,-1.371810,1.394295,0.052309,0.753410,-1.743360,-0.356218,0.123351,-1.677714
4,0.347489,-0.259215,1.391204,1.041557,0.179403,-0.884425,1.388264,-0.844960,1.435685,1.035333,...,1.014998,-0.274386,0.380356,-0.645488,0.121547,-1.161677,-0.975405,0.066756,-1.213422,-0.003349

In [50]:

import random
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

A = data
b = df3
A_train, A_test, b_train, b_test = train_test_split(A, b, test_size=0.4,random_state=4)

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(A_train, b_train)

b_pred=knn.predict(A_test)
print(metrics.accuracy_score(b_test, b_pred))

0.4523809523809524