In [1]:
10 + 15

25

In [2]:
print("Hello World")

Hello World

In [3]:
45 - 34

11

In [4]:
8 * 2

16

In [5]:
print("Rahul's age is", 45)

Rahul's age is 45

In [6]:
print("I have", 10, "mangoes and", 12, "bananas")

I have 10 mangoes and 12 bananas

In [7]:
emp_number = 1233
print("Employee Number:", emp_number)
emp_salary = 16745.50
emp_name = "Jerry Squaris"
print("Employee Salary and Name:", emp_salary, emp_name)
emp_salary = 23450.34
print("Updated Employee Salary:", emp_salary)

Employee Number: 1233
Employee Salary and Name: 16745.5 Jerry Squaris
Updated Employee Salary: 23450.34

In [2]:
customer_id = 101
type(customer_id)
customer_name = "John"
type(customer_name)
bill_amount = 675.45
type(bill_amount )
x = 5.3 + 0.9j
type(x)
print(customer_id, customer_name, bill_amount)
print(x.real)
print(x.imag + 3) 
Flag = True
type(Flag)
y = "False"

101 John 675.45
5.3
3.9

In [1]:
bill_id = 101
print(bill_id)
customer_id = 1001
print(customer_id)
customer_name = "Rahul"
print(customer_name)
if_minor = False
bill_amount = 2000.50
print(bill_amount)

101
1001
Rahul
2000.5

In [11]:
# Store input numbers
num1 = int(input('Enter first number:'))
num2 = int(input('Enter second number:'))

# Add 4 and 6 to the two numbers
num1 += 4
num2 += 6


# Display the numbers
print('The value of num 1 now is',num1)

print('The value of num 2 now is',num2)

Enter first number: 4
Enter second number: 5

The value of num 1 now is 8
The value of num 2 now is 11

In [14]:
# Python program to swap two variables

a = 4
b = 5
#  swapping the values
a = a + b
b = a - b
a = a - b
#printing the Swapped values
print('The value of a now is',a)
print('The value of b now is',b)

The value of a now is 5
The value of b now is 4

In [9]:
sub1=int(input("Enter marks of the first subject: "))
sub2=int(input("Enter marks of the second subject: "))
sub3=int(input("Enter marks of the third subject: "))
avg=(sub1+sub2+sub3)/5
print(avg)
sub1 = 97
print("After Changing Subject1")
print(avg)

Enter marks of the first subject:  92
Enter marks of the second subject:  87
Enter marks of the third subject:  96

55.0
After Changing Subject1
55.0

In [20]:
pi = 3.14
r = float(input ("Enter radius of circle : "))
print ("Area of the circle is: " + str(pi * r**2))
print ("Perimeter of the circle is: " + str(2*pi*r))

Enter radius of circle :  4

Area of the circle is: 50.24
Perimeter of the circle is: 25.12

In [3]:
No_of_Hours = int(input("Enter The No. Of Hours Employee worked"))
if(No_of_Hours > 40 or No_of_Hours < 0):
    print("Invalid Input")
else:
    print("No Of Hours Enterd Is:",No_of_Hours)
Pay_Rate = 400
print("Pay Rate is :",Pay_Rate)
No_of_weeks = 4
print("NO Of Weeks Is Considered AS 4:",No_of_weeks)
Monthly_sal = No_of_Hours * Pay_Rate * No_of_weeks
print("Your Salary Calculated For The Month Is:",Monthly_sal)

Enter The No. Of Hours Employee worked 34

No Of Hours Enterd Is: 34
Pay Rate is : 400
NO Of Weeks Is Considered AS 4: 4
Your Salary Calculated For The Month Is: 54400

In [7]:
# 1.Python program to print Even Numbers in given range
print("1.Python program to print Even Numbers in given range")
start, end = 50, 80


for num in range(start, end + 1):
	

	if num % 2 == 0:
		print(num, end = " ")
print("\n")
  
# 2.Python program to print  Sum of N natural Numbers in given range

print("\n2.Python program to print  Sum of N natural Numbers in given range")

num = int(input("Enter a number: "))  
if num < 0:  
   print("Enter a positive number")  
else:  
   sum = 0  
   #  while loop to iterate  till zero  
   while(num > 0):  
       sum += num  
       num -= 1  
   print("The sum is",sum)  

# 3.Program to check if a number is prime or not
print("\n3.Program to check if a number is prime or not")
num =int(input("Enter The Number:"))

# define a flag variable
flag = False

# prime numbers are greater than 1
if num > 1:
    # check for factors
    for i in range(2, num):
        if (num % i) == 0:
            # if condition is True, set flag to True
            flag = True
            # break out of loop
            break

# check if flag is True
if flag:
    print(num, "is not a prime number")
else:
    print(num, "is a prime number")
    
# 4.Program to display the Fibonacci sequence up to n-th term
print("\n4.Program to display the Fibonacci sequence up to n-th term")
upton = int(input("Enter The Range"))

# first two terms
n1, n2 = 0, 1
count = 0

# check if the number of terms is valid
if upton <= 0:
   print("Please enter a positive integer")
elif upton == 1:
   print("Fibonacci sequence upto",upton,":")
   print(n1)
else:
   print("Fibonacci sequence is:")
   while count < upton:
       print(n1)
       nth = n1 + n2
       # update values
       n1 = n2
       n2 = nth
       count += 1

1.Python program to print Even Numbers in given range
50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80


2.Python program to print  Sum of N natural Numbers in given range

Enter a number:  42

The sum is 903

3.Program to check if a number is prime or not

Enter The Number: 17

17 is a prime number

4.Program to display the Fibonacci sequence up to n-th term

Enter The Range 9

Fibonacci sequence is:
0
1
1
2
3
5
8
13
21